-- Migration 0030: Intentional no-op for legacy Facebook Ads provenance.
-- Ambiguous legacy synced rows retain source_account_id = NULL so that
-- syncMetaAds() reconciles provenance using remote Graph API evidence (D25).
