export const APP_LANGUAGES = ['en', 'vi', 'ja'] as const;
export type AppLanguage = typeof APP_LANGUAGES[number];
export const APP_LANGUAGE_STORAGE_KEY = '1person.appLanguage';

export const APP_LANGUAGE_LABELS: Record<AppLanguage, string> = {
  en: 'English',
  vi: 'Tiếng Việt',
  ja: '日本語',
};

const ALIASES: Record<string, AppLanguage> = {
  en: 'en',
  english: 'en',
  vi: 'vi',
  vietnamese: 'vi',
  'tiếng việt': 'vi',
  'tieng viet': 'vi',
  ja: 'ja',
  jp: 'ja',
  japanese: 'ja',
  nihongo: 'ja',
  '日本語': 'ja',
};

export function normalizeAppLanguage(value?: unknown): AppLanguage {
  const normalized = String(value ?? '').trim().toLowerCase();
  return ALIASES[normalized] ?? 'en';
}

const messages = {
  en: {
    searchPlaceholder: 'Search agents, tasks...',
    guidedTour: 'Guided tour',
    runGuidedTour: 'Run the guided tour',
    tourStep: 'Step',
    tourOf: 'of',
    tourRemaining: 'remaining',
    tourSkip: 'Skip tour',
    tourSkipAll: 'Skip all',
    tourFinish: 'Finish',
    tourGotIt: 'Got it',
    tourNext: 'Next',
    tourOpeningWalkthrough: 'Opening Walkthrough...',
    tourPreparingNextStep: 'Preparing the next guide step...',
    tourDashboardTitle: 'Start with the big picture',
    tourDashboardDesc: 'Dashboard shows what is happening in this company: priorities, progress, AI team activity, and the next useful thing to do.',
    tourWalkthroughTitle: 'Use the setup guide',
    tourWalkthroughDesc: 'Walkthrough turns the product into a simple checklist, so you know where to start and what to set up first.',
    tourQuickStartTitle: 'Follow Quick Start',
    tourQuickStartDesc: 'This checklist helps you get real value quickly: add knowledge, review your brand, create a page, and connect the tools AI needs.',
    tourKnowledgeTitle: 'Teach AI your business',
    tourKnowledgeDesc: 'Knowledge Hub is where you add product details, FAQs, documents, offers, and internal notes that AI should trust.',
    tourBrainTitle: 'See what AI has learned',
    tourBrainDesc: 'Brain Hub shows the sources, signals, and business context AI is using, so recommendations stay grounded in your real company.',
    tourLandingPagesTitle: 'Create a page to send customers to',
    tourLandingPagesDesc: 'Landing Pages helps you build a focused public page for an offer, campaign, product, or lead generation without needing a developer.',
    tourMarketTitle: 'Understand competitors and demand',
    tourMarketDesc: 'Market & Competitors helps AI compare your business with the market, spot gaps, and find opportunities worth acting on.',
    tourCeoAdvisorTitle: 'Ask for strategic next steps',
    tourCeoAdvisorDesc: 'CEO Advisor reads your company context, knowledge, campaigns, blogs, and market signals, then suggests the highest-impact actions.',
    tourCampaignLauncherTitle: 'Turn strategy into a campaign',
    tourCampaignLauncherDesc: 'Campaign Launcher creates a practical marketing package from your inputs: blog content, social posts, banners, and campaign assets.',
    tourAnalyticsTitle: 'Measure what is working',
    tourAnalyticsDesc: 'Analytics helps you see performance after campaigns and pages go live, so you can improve based on results instead of guessing.',
    campaignsTourCreateTitle: 'Create your first campaign',
    campaignsTourCreateDesc: 'Click Generate Campaign at the top right. Tell the AI your goal and audience, and it will build banners, ads, and social posts in one click.',
    campaignsTourBrainTitle: 'Your Business Brain',
    campaignsTourBrainDesc: 'Everything the AI writes comes from what it knows about your brand, customers, and products. Keep your Brain updated for better results.',
    campaignsTourTrustTitle: 'Tamper-proof trust log',
    campaignsTourTrustDesc: 'Every AI action is recorded and cryptographically verified. You can always see what the AI did, when, and why.',
    aiActive: 'AI Active',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
    active: 'Active',
    dashboard: 'Dashboard',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    createCompanyFirst: 'Create a company first',
    unlocksAtLevel: 'Unlocks at Level',
    createNewPage: 'Create New Page',
    getStarted: 'Get Started',
    companyLanguage: 'Content Language',
    companyLanguageHelp: 'AI will generate banners, posts, pages, and recommendations in this language.',
    languageSaved: 'Language updated',
    languageSaveFailed: 'Could not update language',
    navBusinessStrategy: 'Business Strategy',
    navAiTeam: 'AI Team',
    navExecution: 'Execution',
    navAnalytics: 'Analytics',
    navSystem: 'System',
    navGrowthPlan: 'Growth Plan',
    navBrandIq: 'Brand IQ',
    navCeoAdvisor: 'CEO Advisor',
    navWalkthrough: 'Walkthrough',
    navYourAiTeam: 'Your AI Team',
    navKnowledgeHub: 'Knowledge Hub',
    navBrainHub: 'Brain Hub',
    navCampaigns: 'Campaigns',
    navCampaignLauncher: 'Campaign Launcher',
    navLandingPages: 'Landing Pages',
    navContentAutopilot: 'Content Autopilot',
    navContentEditor: 'Content Editor',
    navAiVisibility: 'AI Visibility (GEO)',
    navMarket: 'Market & Competitors',
    navPlaybooks: 'Marketing Playbooks',
    navSales: 'Sales',
    navSocialMedia: 'Social Media',
    navChannels: 'Channels',
    navInbox: 'Inbox & Messages',
    navChatbot: 'Chatbot',
    navAssets: 'Assets',
    navBrain: 'Brain',
    navTrust: 'Trust',
    navCredits: 'Credits & Billing',
    navAdmin: 'Admin',
    welcomeStartTitle: 'How would you like to start?',
    welcomeStartSubtitle: 'AI will handle everything. Just tell us where you are.',
    language: 'Language',
    startingFresh: "I'm starting fresh",
    startingFreshDesc: 'Describe your idea and AI will create pages, content, and a marketing plan.',
    haveWebsite: 'I have a website',
    haveWebsiteDesc: 'Paste your URL and AI will analyze it, find improvements, and grow your traffic.',
    describeBusinessIdea: 'Describe your business idea',
    pasteWebsiteUrl: 'Paste your website URL',
    businessIdeaHelp: 'AI will create landing pages, content, and a growth plan automatically.',
    websiteUrlHelp: 'AI will crawl your site, audit SEO, and create an improvement plan.',
    businessIdeaPlaceholder: 'e.g. A fitness coaching platform for busy professionals...',
    websiteUrlPlaceholder: 'e.g. kidleaderhub.com',
    addMoreBusinessDetail: 'Please add a little more detail about your business',
    moreCharacters: 'more characters',
    websiteDetected: 'Website detected',
    businessIdea: 'Business idea',
    back: 'Back',
    building: 'Building...',
    analyzeAndGrow: 'Analyze & Grow',
    createMyBusiness: 'Create My Business',
    buildingAiCompany: 'Building Your AI Company...',
    creatingPersonalizedTeam: 'Creating your personalized AI team',
    setupCouldNotFinish: 'Setup could not finish',
    backAndTryAgain: 'Back and try again',
    aiIsThinking: 'AI is thinking...',
    analyzingBusinessIdea: 'Analyzing your business idea...',
    detected: 'Detected:',
    market: 'Market',
    model: 'Model',
    strategy: 'Strategy',
    progress: 'Progress',
    buildingPrompt: 'Building',
    stepUnderstanding: 'Understanding your business...',
    stepAnalyzingWebsite: 'Crawling and analyzing your website...',
    stepCreatingCeo: 'Creating your CEO agent...',
    stepCreatingMarketing: 'Building marketing team...',
    stepCreatingOperations: 'Setting up operations...',
    stepGeneratingStrategy: 'Generating growth strategy...',
    stepSettingUpBrand: 'Setting up brand identity...',
    understandBusinessTitle: 'We understand your business',
    understandBusinessDesc: 'Confirm these details so we can build the right AI team.',
    aiConfidence: 'AI Confidence',
    cancel: 'Cancel',
    edit: 'Edit',
    companyName: 'Company name',
    industry: 'Industry',
    businessModel: 'Business model',
    targetAudience: 'Target Audience',
    productsServices: 'Products or services',
    businessValue: 'What makes your business valuable?',
    growthDirection: 'Growth direction',
    saveChanges: 'Save changes',
    saving: 'Saving...',
    coreOfferings: 'Core Offerings',
    valueProposition: 'Value Proposition',
    websiteSeoScore: 'Website SEO Score',
    issuesFound: 'Issues Found:',
    moreIssues: 'more issues',
    socialProfilesDetected: 'Social Profiles Detected',
    preparingCompanyIntelligence: 'Preparing your company intelligence',
    preparingCompanyIntelligenceDesc: 'One setup now, so Brand IQ and CEO Advisor are ready when you arrive.',
    estimated: 'Estimated',
    finalGrowthPlan: 'Building your Growth Plan',
    finalGrowthPlanDesc: 'Turning your business context into practical priorities.',
    finalBrandIq: 'Creating your Brand IQ',
    finalBrandIqDesc: 'Defining audience, positioning, voice, and brand guidance.',
    finalAdvisor: 'Preparing your first CEO advice',
    finalAdvisorDesc: 'Prioritizing the most useful next actions for your company.',
    finalSave: 'Saving and checking everything',
    finalSaveDesc: 'Making sure your company intelligence is ready to use.',
    finalKeepOpen: 'This may take about a minute. Please keep this page open while AI prepares the shared context.',
    startOver: 'Start Over',
    confirmBuildTeam: 'Confirm & Build My Team',
    aiTeamReady: 'Your AI Team is Ready!',
    aiAgentsFor: 'AI agents for',
    changeTeamQuestion: 'Want to change the team? Tell us what you need',
    describeTeamChange: "Describe what you'd like to change",
    teamChangeExample: 'E.g. "Add a customer support agent under Carol Lee" or "I need a content writer in the marketing team"',
    teamChangePlaceholder: 'I need a customer support person...',
    continue: 'Continue',
    growthMasterPlan: 'Your Growth Master Plan',
    growthMasterPlanDesc: 'AI has designed a comprehensive strategy for',
    approvingPlan: 'Approving plan...',
    approvePlan: 'Approve Plan',
    readyToLaunch: 'Ready to launch?',
    readyToLaunchDesc: 'Your AI team will start executing the growth plan for',
    seoEngine: 'SEO Engine',
    seoEngineDesc: 'Optimize and track rankings',
    contentEngine: 'Content Engine',
    contentEngineDesc: 'Create SEO articles and pages',
    socialEngine: 'Social Engine',
    socialEngineDesc: 'Schedule and post content',
    activatingAiTeam: 'Activating AI Team...',
    startGrowingCompany: 'Start Growing My Company',
    agentsAutonomous: 'Your AI agents will begin working autonomously',
    aiCompanyLive: 'Your AI Company is Live!',
    readyToOperate: 'is ready to operate',
    agentsActive: 'Agents Active',
    monthlyBudget: 'Monthly Budget',
    tasksScheduled: 'Tasks Scheduled',
    goToCeoDashboard: 'Go to CEO Dashboard',
    redirectingIn: 'Redirecting in',
    seconds: 'seconds',
    goToDashboard: 'Go to Dashboard',
    completeStepsAnytime: 'You can complete these steps anytime',
  },
  vi: {
    searchPlaceholder: 'Tìm agent, tác vụ...',
    guidedTour: 'Hướng dẫn',
    runGuidedTour: 'Xem lại hướng dẫn',
    tourStep: 'Bước',
    tourOf: '/',
    tourRemaining: 'còn lại',
    tourSkip: 'Bỏ qua hướng dẫn',
    tourSkipAll: 'Bỏ qua tất cả',
    tourFinish: 'Hoàn tất',
    tourGotIt: 'Đã hiểu',
    tourNext: 'Tiếp theo',
    tourOpeningWalkthrough: 'Đang mở Walkthrough...',
    tourPreparingNextStep: 'Đang chuẩn bị bước tiếp theo...',
    tourDashboardTitle: 'Bắt đầu từ bức tranh tổng thể',
    tourDashboardDesc: 'Dashboard cho bạn thấy điều đang diễn ra trong công ty: ưu tiên, tiến độ, hoạt động của AI team và việc nên làm tiếp theo.',
    tourWalkthroughTitle: 'Dùng hướng dẫn thiết lập',
    tourWalkthroughDesc: 'Walkthrough biến hệ thống thành checklist đơn giản để bạn biết nên bắt đầu từ đâu và cần thiết lập gì trước.',
    tourQuickStartTitle: 'Đi theo Quick Start',
    tourQuickStartDesc: 'Checklist này giúp bạn nhận giá trị nhanh: thêm kiến thức, kiểm tra thương hiệu, tạo trang và kết nối các công cụ AI cần.',
    tourKnowledgeTitle: 'Dạy AI về doanh nghiệp của bạn',
    tourKnowledgeDesc: 'Knowledge Hub là nơi thêm thông tin sản phẩm, FAQ, tài liệu, ưu đãi và ghi chú nội bộ mà AI nên tin dùng.',
    tourBrainTitle: 'Xem AI đã học được gì',
    tourBrainDesc: 'Brain Hub hiển thị nguồn dữ liệu, tín hiệu và bối cảnh kinh doanh mà AI đang dùng để đề xuất sát với công ty thật của bạn.',
    tourLandingPagesTitle: 'Tạo trang để gửi khách hàng tới',
    tourLandingPagesDesc: 'Landing Pages giúp bạn tạo trang công khai cho ưu đãi, chiến dịch, sản phẩm hoặc thu lead mà không cần developer.',
    tourMarketTitle: 'Hiểu đối thủ và nhu cầu thị trường',
    tourMarketDesc: 'Market & Competitors giúp AI so sánh doanh nghiệp với thị trường, phát hiện khoảng trống và cơ hội đáng hành động.',
    tourCeoAdvisorTitle: 'Nhận bước đi chiến lược tiếp theo',
    tourCeoAdvisorDesc: 'CEO Advisor đọc dữ liệu công ty, Knowledge, campaigns, blogs và tín hiệu thị trường để đề xuất hành động có tác động cao nhất.',
    tourCampaignLauncherTitle: 'Biến chiến lược thành campaign',
    tourCampaignLauncherDesc: 'Campaign Launcher tạo bộ marketing thực tế từ input của bạn: blog, social posts, banners và tài sản chiến dịch.',
    tourAnalyticsTitle: 'Đo lường điều đang hiệu quả',
    tourAnalyticsDesc: 'Analytics giúp bạn xem hiệu suất sau khi campaign và landing page được publish để cải thiện bằng dữ liệu thay vì đoán.',
    campaignsTourCreateTitle: 'Tạo campaign đầu tiên',
    campaignsTourCreateDesc: 'Bấm Generate Campaign ở góc phải. Nhập mục tiêu và khách hàng, AI sẽ tạo banners, ads và social posts trong một lần.',
    campaignsTourBrainTitle: 'Business Brain của bạn',
    campaignsTourBrainDesc: 'Mọi nội dung AI viết đều dựa trên hiểu biết về thương hiệu, khách hàng và sản phẩm. Cập nhật Brain để kết quả tốt hơn.',
    campaignsTourTrustTitle: 'Nhật ký tin cậy chống chỉnh sửa',
    campaignsTourTrustDesc: 'Mọi hành động AI được ghi lại và xác minh bằng mã hoá. Bạn luôn biết AI đã làm gì, khi nào và vì sao.',
    aiActive: 'AI đang hoạt động',
    profile: 'Hồ sơ',
    settings: 'Cài đặt',
    logout: 'Đăng xuất',
    active: 'Đang hoạt động',
    dashboard: 'Bảng điều khiển',
    openMenu: 'Mở menu',
    closeMenu: 'Đóng menu',
    createCompanyFirst: 'Tạo công ty trước',
    unlocksAtLevel: 'Mở khóa ở Level',
    createNewPage: 'Tạo trang mới',
    getStarted: 'Bắt đầu',
    companyLanguage: 'Ngôn ngữ nội dung',
    companyLanguageHelp: 'AI sẽ tạo banner, bài đăng, trang và đề xuất bằng ngôn ngữ này.',
    languageSaved: 'Đã cập nhật ngôn ngữ',
    languageSaveFailed: 'Không thể cập nhật ngôn ngữ',
    navBusinessStrategy: 'Chiến lược kinh doanh',
    navAiTeam: 'Đội AI',
    navExecution: 'Thực thi',
    navAnalytics: 'Phân tích',
    navSystem: 'Hệ thống',
    navGrowthPlan: 'Kế hoạch tăng trưởng',
    navBrandIq: 'Brand IQ',
    navCeoAdvisor: 'Cố vấn CEO',
    navWalkthrough: 'Hướng dẫn sử dụng',
    navYourAiTeam: 'Đội AI của bạn',
    navKnowledgeHub: 'Kho tri thức',
    navBrainHub: 'Brain Hub',
    navCampaigns: 'Chiến dịch',
    navCampaignLauncher: 'Tạo chiến dịch',
    navLandingPages: 'Landing Pages',
    navContentAutopilot: 'Tự động nội dung',
    navContentEditor: 'Chỉnh sửa nội dung',
    navAiVisibility: 'Hiển thị AI (GEO)',
    navMarket: 'Thị trường & Đối thủ',
    navPlaybooks: 'Playbook marketing',
    navSales: 'Bán hàng',
    navSocialMedia: 'Mạng xã hội',
    navChannels: 'Kênh kết nối',
    navInbox: 'Inbox & Tin nhắn',
    navChatbot: 'Chatbot',
    navAssets: 'Tài sản',
    navBrain: 'Brain',
    navTrust: 'Niềm tin',
    navCredits: 'Credits & Thanh toán',
    navAdmin: 'Admin',
    welcomeStartTitle: 'Bạn muốn bắt đầu như thế nào?',
    welcomeStartSubtitle: 'AI sẽ hỗ trợ phần còn lại. Hãy cho chúng tôi biết bạn đang ở đâu.',
    language: 'Ngôn ngữ',
    startingFresh: 'Tôi đang bắt đầu từ đầu',
    startingFreshDesc: 'Mô tả ý tưởng, AI sẽ tạo trang, nội dung và kế hoạch marketing.',
    haveWebsite: 'Tôi đã có website',
    haveWebsiteDesc: 'Dán URL, AI sẽ phân tích website, tìm điểm cải thiện và giúp tăng trưởng.',
    describeBusinessIdea: 'Mô tả ý tưởng kinh doanh',
    pasteWebsiteUrl: 'Dán URL website',
    businessIdeaHelp: 'AI sẽ tự động tạo landing page, nội dung và growth plan.',
    websiteUrlHelp: 'AI sẽ crawl website, audit SEO và tạo kế hoạch cải thiện.',
    businessIdeaPlaceholder: 'VD: Nền tảng coaching fitness cho người đi làm bận rộn...',
    websiteUrlPlaceholder: 'VD: kidleaderhub.com',
    addMoreBusinessDetail: 'Vui lòng mô tả doanh nghiệp chi tiết hơn một chút',
    moreCharacters: 'ký tự nữa',
    websiteDetected: 'Đã nhận diện website',
    businessIdea: 'Ý tưởng kinh doanh',
    back: 'Quay lại',
    building: 'Đang tạo...',
    analyzeAndGrow: 'Phân tích & tăng trưởng',
    createMyBusiness: 'Tạo doanh nghiệp của tôi',
    buildingAiCompany: 'Đang xây dựng AI Company...',
    creatingPersonalizedTeam: 'Đang tạo đội AI riêng cho bạn',
    setupCouldNotFinish: 'Không thể hoàn tất thiết lập',
    backAndTryAgain: 'Quay lại và thử lại',
    aiIsThinking: 'AI đang suy nghĩ...',
    analyzingBusinessIdea: 'Đang phân tích ý tưởng kinh doanh...',
    detected: 'Đã phát hiện:',
    market: 'Thị trường',
    model: 'Mô hình',
    strategy: 'Chiến lược',
    progress: 'Tiến độ',
    buildingPrompt: 'Đang tạo',
    stepUnderstanding: 'Đang hiểu doanh nghiệp của bạn...',
    stepAnalyzingWebsite: 'Đang crawl và phân tích website...',
    stepCreatingCeo: 'Đang tạo CEO agent...',
    stepCreatingMarketing: 'Đang xây dựng đội marketing...',
    stepCreatingOperations: 'Đang thiết lập vận hành...',
    stepGeneratingStrategy: 'Đang tạo chiến lược tăng trưởng...',
    stepSettingUpBrand: 'Đang thiết lập nhận diện thương hiệu...',
    understandBusinessTitle: 'Chúng tôi đã hiểu doanh nghiệp của bạn',
    understandBusinessDesc: 'Xác nhận thông tin này để xây dựng đội AI phù hợp.',
    aiConfidence: 'Độ tin cậy AI',
    cancel: 'Hủy',
    edit: 'Chỉnh sửa',
    companyName: 'Tên công ty',
    industry: 'Ngành',
    businessModel: 'Mô hình kinh doanh',
    targetAudience: 'Khách hàng mục tiêu',
    productsServices: 'Sản phẩm hoặc dịch vụ',
    businessValue: 'Điều làm doanh nghiệp có giá trị',
    growthDirection: 'Định hướng tăng trưởng',
    saveChanges: 'Lưu thay đổi',
    saving: 'Đang lưu...',
    coreOfferings: 'Sản phẩm/dịch vụ chính',
    valueProposition: 'Giá trị khác biệt',
    websiteSeoScore: 'Điểm SEO website',
    issuesFound: 'Vấn đề tìm thấy:',
    moreIssues: 'vấn đề khác',
    socialProfilesDetected: 'Social profiles đã phát hiện',
    preparingCompanyIntelligence: 'Đang chuẩn bị trí tuệ doanh nghiệp',
    preparingCompanyIntelligenceDesc: 'Thiết lập một lần để Brand IQ và CEO Advisor sẵn sàng khi bạn vào hệ thống.',
    estimated: 'Ước tính',
    finalGrowthPlan: 'Đang xây dựng Growth Plan',
    finalGrowthPlanDesc: 'Biến bối cảnh kinh doanh thành các ưu tiên thực tế.',
    finalBrandIq: 'Đang tạo Brand IQ',
    finalBrandIqDesc: 'Xác định khách hàng, định vị, giọng nói thương hiệu và hướng dẫn brand.',
    finalAdvisor: 'Đang chuẩn bị CEO advice đầu tiên',
    finalAdvisorDesc: 'Ưu tiên các hành động hữu ích nhất cho công ty.',
    finalSave: 'Đang lưu và kiểm tra mọi thứ',
    finalSaveDesc: 'Đảm bảo trí tuệ doanh nghiệp đã sẵn sàng sử dụng.',
    finalKeepOpen: 'Có thể mất khoảng một phút. Vui lòng giữ trang này mở trong lúc AI chuẩn bị context chung.',
    startOver: 'Làm lại từ đầu',
    confirmBuildTeam: 'Xác nhận & xây dựng đội AI',
    aiTeamReady: 'Đội AI của bạn đã sẵn sàng!',
    aiAgentsFor: 'AI agents cho',
    changeTeamQuestion: 'Muốn thay đổi đội AI? Hãy cho chúng tôi biết bạn cần gì',
    describeTeamChange: 'Mô tả điều bạn muốn thay đổi',
    teamChangeExample: 'VD: "Thêm nhân viên hỗ trợ khách hàng dưới Carol Lee" hoặc "Tôi cần content writer trong team marketing"',
    teamChangePlaceholder: 'Tôi cần một người phụ trách hỗ trợ khách hàng...',
    continue: 'Tiếp tục',
    growthMasterPlan: 'Growth Master Plan của bạn',
    growthMasterPlanDesc: 'AI đã thiết kế chiến lược tổng thể cho',
    approvingPlan: 'Đang duyệt plan...',
    approvePlan: 'Duyệt plan',
    readyToLaunch: 'Sẵn sàng triển khai?',
    readyToLaunchDesc: 'Đội AI sẽ bắt đầu thực thi growth plan cho',
    seoEngine: 'SEO Engine',
    seoEngineDesc: 'Tối ưu và theo dõi thứ hạng',
    contentEngine: 'Content Engine',
    contentEngineDesc: 'Tạo bài SEO và trang nội dung',
    socialEngine: 'Social Engine',
    socialEngineDesc: 'Lên lịch và đăng nội dung',
    activatingAiTeam: 'Đang kích hoạt đội AI...',
    startGrowingCompany: 'Bắt đầu tăng trưởng công ty',
    agentsAutonomous: 'Các AI agent sẽ bắt đầu làm việc tự động',
    aiCompanyLive: 'AI Company của bạn đã hoạt động!',
    readyToOperate: 'đã sẵn sàng vận hành',
    agentsActive: 'Agents đang hoạt động',
    monthlyBudget: 'Ngân sách tháng',
    tasksScheduled: 'Tác vụ đã lên lịch',
    goToCeoDashboard: 'Đi tới CEO Dashboard',
    redirectingIn: 'Chuyển hướng trong',
    seconds: 'giây',
    goToDashboard: 'Đi tới Dashboard',
    completeStepsAnytime: 'Bạn có thể hoàn tất các bước này bất cứ lúc nào',
  },
  ja: {
    searchPlaceholder: 'エージェントやタスクを検索...',
    guidedTour: 'ガイド',
    runGuidedTour: 'ガイドをもう一度見る',
    tourStep: 'ステップ',
    tourOf: '/',
    tourRemaining: '残り',
    tourSkip: 'ガイドをスキップ',
    tourSkipAll: 'すべてスキップ',
    tourFinish: '完了',
    tourGotIt: '了解',
    tourNext: '次へ',
    tourOpeningWalkthrough: '使い方ガイドを開いています...',
    tourPreparingNextStep: '次のガイドを準備しています...',
    tourDashboardTitle: 'まず全体像を確認しましょう',
    tourDashboardDesc: 'ダッシュボードでは、この会社の優先事項、進捗、AIチームの動き、次に行うべきことを確認できます。',
    tourWalkthroughTitle: 'セットアップガイドを使いましょう',
    tourWalkthroughDesc: 'Walkthrough は、最初に何を設定すればよいかをチェックリスト形式で案内します。',
    tourQuickStartTitle: 'Quick Start に沿って進めましょう',
    tourQuickStartDesc: '知識を追加し、ブランドを確認し、ページを作成し、AIに必要な連携を整えることで、早く価値を体験できます。',
    tourKnowledgeTitle: 'AIに事業内容を教えましょう',
    tourKnowledgeDesc: 'Knowledge Hub には、商品情報、FAQ、資料、オファー、社内メモなど、AIが信頼すべき情報を追加します。',
    tourBrainTitle: 'AIが学習した内容を確認しましょう',
    tourBrainDesc: 'Brain Hub では、AIが利用している情報源、シグナル、事業コンテキストを確認できます。',
    tourLandingPagesTitle: '顧客を送るページを作りましょう',
    tourLandingPagesDesc: 'Landing Pages では、オファー、キャンペーン、商品、リード獲得向けの公開ページを開発者なしで作成できます。',
    tourMarketTitle: '競合と需要を理解しましょう',
    tourMarketDesc: 'Market & Competitors は、市場と競合を比較し、AIがギャップや実行すべき機会を見つけるのに役立ちます。',
    tourCeoAdvisorTitle: '次の戦略アクションを確認しましょう',
    tourCeoAdvisorDesc: 'CEO Advisor は会社情報、Knowledge、キャンペーン、ブログ、市場シグナルを読み取り、重要度の高いアクションを提案します。',
    tourCampaignLauncherTitle: '戦略をキャンペーンに変えましょう',
    tourCampaignLauncherDesc: 'Campaign Launcher は入力内容から、ブログ、SNS投稿、バナー、キャンペーン素材をまとめて作成します。',
    tourAnalyticsTitle: '成果を測定しましょう',
    tourAnalyticsDesc: 'Analytics では、キャンペーンやページ公開後の成果を確認し、推測ではなくデータに基づいて改善できます。',
    campaignsTourCreateTitle: '最初のキャンペーンを作成しましょう',
    campaignsTourCreateDesc: '右上の Generate Campaign をクリックし、目的と対象顧客を入力すると、AIがバナー、広告、SNS投稿をまとめて作成します。',
    campaignsTourBrainTitle: 'Business Brain を育てましょう',
    campaignsTourBrainDesc: 'AIが作成する内容は、ブランド、顧客、商品について知っている情報に基づきます。Brain を更新すると結果が良くなります。',
    campaignsTourTrustTitle: '信頼できる操作ログ',
    campaignsTourTrustDesc: 'AIの操作は記録され、検証できます。AIが何を、いつ、なぜ行ったかをいつでも確認できます。',
    aiActive: 'AI稼働中',
    profile: 'プロフィール',
    settings: '設定',
    logout: 'ログアウト',
    active: '稼働中',
    dashboard: 'ダッシュボード',
    openMenu: 'メニューを開く',
    closeMenu: 'メニューを閉じる',
    createCompanyFirst: '先に会社を作成してください',
    unlocksAtLevel: 'レベルで解放',
    createNewPage: '新しいページを作成',
    getStarted: 'はじめる',
    companyLanguage: 'コンテンツ言語',
    companyLanguageHelp: 'AIはバナー、投稿、ページ、提案をこの言語で生成します。',
    languageSaved: '言語を更新しました',
    languageSaveFailed: '言語を更新できませんでした',
    navBusinessStrategy: '事業戦略',
    navAiTeam: 'AIチーム',
    navExecution: '実行',
    navAnalytics: '分析',
    navSystem: 'システム',
    navGrowthPlan: '成長プラン',
    navBrandIq: 'ブランドIQ',
    navCeoAdvisor: 'CEOアドバイザー',
    navWalkthrough: '使い方ガイド',
    navYourAiTeam: 'AIチーム',
    navKnowledgeHub: 'ナレッジハブ',
    navBrainHub: 'ブレインハブ',
    navCampaigns: 'キャンペーン',
    navCampaignLauncher: 'キャンペーン作成',
    navLandingPages: 'ランディングページ',
    navContentAutopilot: 'コンテンツ自動化',
    navContentEditor: 'コンテンツ編集',
    navAiVisibility: 'AI検索可視性',
    navMarket: '市場・競合分析',
    navPlaybooks: 'マーケティング手順書',
    navSales: '営業',
    navSocialMedia: 'SNS',
    navChannels: '連携チャネル',
    navInbox: '受信箱・メッセージ',
    navChatbot: 'チャットボット',
    navAssets: '素材',
    navBrain: 'ブレイン',
    navTrust: '信頼性',
    navCredits: 'クレジット・請求',
    navAdmin: '管理',
    welcomeStartTitle: 'どのように始めますか？',
    welcomeStartSubtitle: 'AIがセットアップを支援します。現在の状況を教えてください。',
    language: '言語',
    startingFresh: 'まだWebサイトがありません',
    startingFreshDesc: '事業アイデアを入力すると、AIがページ、コンテンツ、マーケティング計画を作成します。',
    haveWebsite: 'Webサイトがあります',
    haveWebsiteDesc: 'URLを入力すると、AIがサイトを分析し、改善点と成長施策を提案します。',
    describeBusinessIdea: '事業アイデアを入力してください',
    pasteWebsiteUrl: 'WebサイトURLを入力してください',
    businessIdeaHelp: 'AIがランディングページ、コンテンツ、成長プランを自動で作成します。',
    websiteUrlHelp: 'AIがサイトをクロールし、SEOを診断して改善プランを作成します。',
    businessIdeaPlaceholder: '例：忙しい社会人向けのフィットネスコーチングサービス...',
    websiteUrlPlaceholder: '例：kidleaderhub.com',
    addMoreBusinessDetail: '事業内容をもう少し詳しく入力してください',
    moreCharacters: '文字以上',
    websiteDetected: 'Webサイトを検出しました',
    businessIdea: '事業アイデア',
    back: '戻る',
    building: '作成中...',
    analyzeAndGrow: '分析して成長させる',
    createMyBusiness: '事業を作成',
    buildingAiCompany: 'AIカンパニーを構築中...',
    creatingPersonalizedTeam: 'あなた専用のAIチームを作成しています',
    setupCouldNotFinish: 'セットアップを完了できませんでした',
    backAndTryAgain: '戻ってもう一度試す',
    aiIsThinking: 'AIが考えています...',
    analyzingBusinessIdea: '事業アイデアを分析しています...',
    detected: '検出結果:',
    market: '市場',
    model: 'モデル',
    strategy: '戦略',
    progress: '進捗',
    buildingPrompt: '作成対象',
    stepUnderstanding: '事業内容を理解しています...',
    stepAnalyzingWebsite: 'Webサイトをクロールして分析しています...',
    stepCreatingCeo: 'CEOエージェントを作成しています...',
    stepCreatingMarketing: 'マーケティングチームを構築しています...',
    stepCreatingOperations: '運用体制を設定しています...',
    stepGeneratingStrategy: '成長戦略を生成しています...',
    stepSettingUpBrand: 'ブランド情報を設定しています...',
    understandBusinessTitle: '事業内容を理解しました',
    understandBusinessDesc: '内容を確認すると、最適なAIチームを構築できます。',
    aiConfidence: 'AI信頼度',
    cancel: 'キャンセル',
    edit: '編集',
    companyName: '会社名',
    industry: '業界',
    businessModel: 'ビジネスモデル',
    targetAudience: 'ターゲット顧客',
    productsServices: '商品・サービス',
    businessValue: 'この事業の強み',
    growthDirection: '成長方針',
    saveChanges: '変更を保存',
    saving: '保存中...',
    coreOfferings: '主な提供内容',
    valueProposition: '提供価値',
    websiteSeoScore: 'WebサイトSEOスコア',
    issuesFound: '見つかった課題:',
    moreIssues: '件の追加課題',
    socialProfilesDetected: '検出されたSNSプロフィール',
    preparingCompanyIntelligence: '会社インテリジェンスを準備中',
    preparingCompanyIntelligenceDesc: 'Brand IQとCEO Advisorをすぐ使える状態にしています。',
    estimated: '推定',
    finalGrowthPlan: '成長プランを作成中',
    finalGrowthPlanDesc: '事業データを実行しやすい優先事項に変換しています。',
    finalBrandIq: 'Brand IQを作成中',
    finalBrandIqDesc: '顧客、ポジショニング、声のトーン、ブランド方針を整理しています。',
    finalAdvisor: '最初のCEOアドバイスを準備中',
    finalAdvisorDesc: '今もっとも有効な次のアクションを優先順位づけしています。',
    finalSave: '保存と確認を実行中',
    finalSaveDesc: '会社インテリジェンスが利用可能か確認しています。',
    finalKeepOpen: '約1分かかる場合があります。AIが共通コンテキストを準備するまで、このページを開いたままにしてください。',
    startOver: '最初からやり直す',
    confirmBuildTeam: '確認してAIチームを作成',
    aiTeamReady: 'AIチームの準備ができました',
    aiAgentsFor: 'AIエージェント:',
    changeTeamQuestion: 'チームを変更しますか？必要なことを教えてください',
    describeTeamChange: '変更したい内容を入力してください',
    teamChangeExample: '例：「カスタマーサポート担当を追加」「マーケティングチームにライターが必要」',
    teamChangePlaceholder: 'カスタマーサポート担当が必要です...',
    continue: '続ける',
    growthMasterPlan: '成長マスタープラン',
    growthMasterPlanDesc: 'AIが包括的な戦略を設計しました:',
    approvingPlan: 'プランを承認中...',
    approvePlan: 'プランを承認',
    readyToLaunch: '実行を開始しますか？',
    readyToLaunchDesc: 'AIチームが成長プランの実行を開始します:',
    seoEngine: 'SEOエンジン',
    seoEngineDesc: '検索順位を最適化し、追跡します',
    contentEngine: 'コンテンツエンジン',
    contentEngineDesc: 'SEO記事とページを作成します',
    socialEngine: 'SNSエンジン',
    socialEngineDesc: 'コンテンツを予約・投稿します',
    activatingAiTeam: 'AIチームを起動中...',
    startGrowingCompany: '会社の成長を開始',
    agentsAutonomous: 'AIエージェントが自律的に作業を開始します',
    aiCompanyLive: 'AIカンパニーが稼働しました',
    readyToOperate: 'は運用準備ができています',
    agentsActive: '稼働エージェント',
    monthlyBudget: '月間予算',
    tasksScheduled: '予定タスク',
    goToCeoDashboard: 'CEOダッシュボードへ',
    redirectingIn: 'リダイレクトまで',
    seconds: '秒',
    goToDashboard: 'ダッシュボードへ',
    completeStepsAnytime: 'これらのステップはいつでも完了できます',
  },
} satisfies Record<AppLanguage, Record<string, string>>;

export type AppMessageKey = keyof typeof messages.en;

export function appT(language: unknown, key: AppMessageKey): string {
  const locale = normalizeAppLanguage(language);
  return messages[locale][key] ?? messages.en[key] ?? key;
}
